// Auto-generated module declarations to silence missing type errors for third-party libs
declare module '@radix-ui/react-accordion'
declare module '@radix-ui/react-aspect-ratio'
declare module '@radix-ui/react-avatar'
declare module '@radix-ui/react-collapsible'
declare module 'embla-carousel-react'
declare module 'cmdk'
declare module '@radix-ui/react-context-menu'
declare module 'vaul'
declare module '@radix-ui/react-dropdown-menu'
declare module 'react-hook-form'
declare module '@radix-ui/react-hover-card'
declare module 'input-otp'
declare module '@radix-ui/react-menubar'
declare module '@radix-ui/react-navigation-menu'
declare module '@radix-ui/react-progress'
declare module '@radix-ui/react-radio-group'
declare module 'react-resizable-panels'
declare module '@radix-ui/react-scroll-area'
declare module '@radix-ui/react-slider'
declare module 'sonner'
declare module '@radix-ui/react-switch'
declare module '@radix-ui/react-toggle-group'
declare module '@radix-ui/react-toggle'
declare module '@radix-ui/react-tooltip'

// Fallback for any other unknown module imports
declare module '*'
